server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/log_analysis?useSSL=true&autoReconnect=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  freemarker:
    cache: false #为了热加载
    charset: utf-8
    content-type: text/html
    enabled: true
    settings:
      number_format: '0'
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**,/customerimages/**;/html/*
mybatis:
  mapper-locations: classpath*:mapper/*.xml

